#!/usr/bin/env bash

packages=(
  .
  packages/ms-web-live-types
  packages/ms-web-live-cms
  packages/ms-web-live-ui
  packages/ms-web-live-app
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L ms-web-live attach
