name: Deploy to Stage

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  publish_packages_to_npm:
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Jake Elder'
          git config user.email 'jake@jakeelder.info'
          git config user.password ${GITHUB_TOKEN}
      - name: Version
        run: yarn version:beta --yes
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn lerna:publish --yes
      - name: Push package.json's and tags
        run: |
          git push --force origin $GITHUB_HEAD_REF
          git push --tags

  deploy_strapi:
    name: Deploy Strapi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID_STAGE }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}
          export_default_credentials: true
      - name: Push to Google Cloud
        env:
          GCLOUD_PROJECT_ID_STAGE: ${{ secrets.GCLOUD_PROJECT_ID_STAGE }}
          GCLOUD_APP_YAML_BASE64: ${{ secrets.GCLOUD_APP_YAML_BASE64_STAGE }}
        run: |
          echo $GCLOUD_APP_YAML_BASE64 | base64 -d > packages/ms-web-live-cms/app.stage.yml
          yarn workspace @mindfulstudio/ms-web-live-cms deploy:stage

  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: publish_packages_to_npm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Get Yarn Cache Dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM Deps
        run: yarn install
      - name: Build
        run: yarn workspace @mindfulstudio/ms-web-live-ui build
      - name: Deploy
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_STAGE: ${{ secrets.VERCEL_UI_PROJECT_ID_STAGE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: yarn workspace @mindfulstudio/ms-web-live-ui deploy:stage

  deploy_next_js_app:
    name: Deploy Next.js app
    needs: publish_packages_to_npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Deploy Build
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_STAGE: ${{ secrets.VERCEL_APP_PROJECT_ID_STAGE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: yarn workspace @mindfulstudio/ms-web-live-app deploy:stage
